### ISSUE TITLE
Bug: Semester create Date selection

### ISSUE THREAD

**Issue by EricZimmer1** [LAM-GeMont/fehlzeiten#117]
The Semester create Date Selection automatically jumps a year ahead. When it's the 01.12.21 it opens a date selection on the 01.12.22

**Comment by bucherfa** [comment]
@EricZimmer1 you mean the end date?

**Comment by EricZimmer1** [comment]
Yes, was that on purpose?

**Comment by bucherfa** [comment]
yes :)

**Comment by EricZimmer1** [comment]
Ok sorry for bothering :)

**Comment by EricZimmer1** [comment]
I think it could be a little irritating because its exactly one year. this might lead to wrong inputs without notice.
