### ISSUE TITLE
Create/Update useraccount based on IServ data

### ISSUE THREAD

**Issue by axelkrusechavela** [LAM-GeMont/fehlzeiten#129]
Basically what to do with the data we get via OAuth.
- Check whether an associated account exists
- If not: create new account
- If yes: check coordinator role and update

**Comment by axelkrusechavela** [comment]
We'll have to think about which is the best property to identify an account. Probably would be uuid. But we could also use email. Maybe even both and if one changes it is updated. That way if the id-pattern or the email-adress is changed by IServ you don't lose access.

**Comment by jonaslanglotz** [comment]
Just a note on this: We cannot just check if the user is a coordinator. We need to make sure students can't login as well.

**Comment by axelkrusechavela** [comment]
Okay yeah, that's quite simple. If someone has the role student just send an error.

But students probably won't know the adress anyway and more important: when we're done with development the right to use OAuth with our application will be removed for students by the IServ Admin.
