### ISSUE TITLE
Make social login the only option

### ISSUE THREAD

**Issue by axelkrusechavela** [LAM-GeMont/fehlzeiten#133]
Remove the old login screen and just put the 'Login with IServ' button.

If someone logs in with IServ he wouldn't even have a passwort as we don't get/save the IServ password.

**Comment by jonaslanglotz** [comment]
We had agreed to keep this feature for now. This is better for development and also allows us to later have admin accounts, which might be important if we want to include user management. But I agree that this might be confusing for users, so we could maybe move the legacy login to a different page and make clear that logging in with iServ is the default.

**Comment by bucherfa** [comment]
becomes relevant once #106 is merged
