### ISSUE TITLE
meta: chrome login not working

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#137]
* windows
* chrome

**Comment by EricZimmer1** [comment]
Error from graphql on login:

``` json
{"errors":[{"message":"Access denied! You need to be authorized to perform this action!","locations":[{"line":2,"column":3}],"path":["self"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Access denied! You need to be authorized to perform this action!","    at C:\\Users\\ericz\\web-projects\\fehlzeiten\\server\\node_modules\\type-graphql\\dist\\helpers\\auth-middleware.js:13:44","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async dispatchHandler (C:\\Users\\ericz\\web-projects\\fehlzeiten\\server\\node_modules\\type-graphql\\dist\\resolvers\\helpers.js:82:24)"]}}}],"data":{"self":null}}
```

**Comment by jonaslanglotz** [comment]
I think this has been thoroughly discussed, see the discord for more info. The reason for this is that we set need to set the cookie attribute sameSite to 'none', which allows us to use Apollo Studio in development. The reason that the login is not working, is that Chrome refuses to allow sameSite:none cookies when secure is set to false. Secure however means that cookies will only be accepted over HTTPS, which we don't use in development. This means that this is unavoidable in development, but will fix itself when we actually deploy, as we will be running on HTTPS and secure will be set to true.

One thing that we should think about however, is that in production we don't want sameSite set to none and we also want to remove 'https://studio.apollographql.com' from the cors origin array. This could be accomplished through the _\_\_PROD\_\__ constant.

**Comment by bucherfa** [comment]
@EricZimmer1 maybe your previous sessions were from before the attribute change?

**Comment by EricZimmer1** [comment]
@bucherfa could be possible. Would be the only explanation
