### ISSUE TITLE
Tutorium Management

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#30]
The application should contain a page, which allows coordinators to manage tutoriums. 

Remaining SP: 13

# Stories
- [x] #21
- [x] #22 
- [x] #23 
- [x] #31
- [x] #44 
- [x] #99 
- [x] #100

**Comment by jonaslanglotz** [comment]
We should add a detail view, so that a user can click on a tutorium in the table and see a better view of the selected tutorium. It should allow us to view the students belonging to the tutor and have functions such as adding and removing students from the tutorium. This needs to be broken down...

- [x] Breakdown complete
- [x] Added User Stories

**Comment by EricZimmer1** [comment]
Please have a look at this issue:

- [ ] #77
