### ISSUE TITLE
Absence Booking

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#4]
The application should allow users to manage student absences.

# Stories
- [x] #51 
- [x] #6
- [x] #69 
- [x] #55 
- [x] #70
- [x] #53 
- [x] #56 
- [x] #7
- [x] #54 
- [x] #8
- [x] #9
- [x] #10
- [x] #12 
- [x] #11 
- [x] #14 
- [x] #83 
- [x] #84 
- [x] #85 
- [x] #96

**Comment by jonaslanglotz** [comment]
We should optionally add a calendar view, that is more intuitive than the list view.

- [ ] Created Tickets

**Comment by bucherfa** [comment]
[Thoughts and Ideas 1](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R7V1bj6M2FP41SO3DVGBzy%2BNMZrZbqZVWGlVV%2B7JywAl0SRxx2bn8%2BtoJhsBxEmYnYMJUGmkYY4P5zrHPdy4wBp6vn39NyTb6g4U0MZAZPhv43kDIshEyxI8ZvpQtluPsW1ZpHJZtdcNj%2FErLRrNsLeKQZo2OOWNJHm%2BbjQHbbGiQN9pImrKnZrclS5p33ZJVeUezbngMSEJBt7%2FiMI%2F2rb5z0PszjVeRvLNllmfWRHYuG7KIhOzpoAk%2FGHieMpbvj9bPc5oI9CQu%2B3GfjpytJpbSTd5lwN2f%2F9h%2Ff45YtvhmfUuIZy9X1o3t7y%2FznSRF%2BcTlbPMXCUHKik1IxVVMA989RXFOH7ckEGefuNR5W5SvE%2F6XxQ%2BzPGXf6JwlLN2NxgvfsR0xcBkniWzfsA0fflfem6Y5fT76VFaFFdcyytY0T194FznA8kuFkhomFeypFheSQokOReWVjaRUkVV18RpFflAC%2BQZQHQAhDblSlX%2ByNI%2FYim1I8lC33jVBrvv8zti2hPZfmucv5QohRc6awNNNeCv0vUaXt3yKxcx3l9zPSUzkNNJ83qxIA3ri%2BeQ6JOmK5if6IbXkUpqQPP7enMfFhWABxX4MImOOjbt5QtMTSm6dV%2FIL6C3GZkNtZybQWgsptNbtS2ndM%2Bt%2B3CqJOqok1qmS3sl9oYRoiqjbOlGffVTUfZ2o2%2Fijwm5rNXue%2FVFx97Tu7QjQjU80Sl5pnGunGp45MqqBlVhluYBlw0%2F8xOH8GapxknCnjw4CmT9rQnbjd8TM7wszG2B2T%2FJiPSqULN0gQWd2ztdafpvdk5eRIaUbKus0Lbp%2BJ1Wied5L1cpO0fToaWfgtRJUOc3RBgjs5pZhazfblQZcaYjA7qqXjla9RJPbEDoD72oFHlKs8VB4a3SbgaNEa0wk3nWboGHtJB65ADT9LN5rcVPcVbd6gwlDQ3PtW6DfcQvEplpWw2yB%2BHTmatLAa%2FUC8PRSA52B12v0YchgQUm64Eaf5js7JqxaLooEdHMAp2XOXE83B8DQhdJvzvxWtNPRbvUxJJb8WbIgKpIwXkFyqROtzkrVH1qQI8X643ctmDxXO0yTixvhrhZDb9wIQ4tB1iLKzNvYUoifP2g2Km2tqtX0ZS%2BgpUAmsm5M8WMgN%2BETuFuk%2FGgljvKU9wKtS5JkimZInThyeRNUksSrDT8OOII05Q0C3zggyW15Yh2H4T7ETbP4lSx2lxIKvmUx36vFdZ07w7kX1%2BKLJNuvF1jwdsHCNrO959hQiv6Q5t6GJVX%2FC%2FFcdaIzNiGiEZORdpZMeyTChlEugNCbymMvoVNVRfGLXIQKmLACJtQbTJCzjRAmrB0m7xpgUlHbQWFyYH3Iimxed94498QF36x3LNH6HggPq9INhEOH%2BqENLAI%2F46MFdt0LgW63dzqV2%2BUoQO%2BvZh06qT9uC%2FSA2mXBy7TFMIrcwXpcG6YKWzMsph1MzbVhqthxh8UU2qUnEQBNAbJZRLbikD8tSRKasFVK1oJg0zTmcxGsvHnuS33ivDCeqXwBTCGc5XKJgkAlnNBduM6lhFOFC2WmVUHYh42yOl1e0YrYelFkb9P4C7o52G6%2BhKWqMbUVoOHeQJsB0BhU52n4mHarOADZ8A24QQmcezp%2Fe%2F21hW65As%2BGKl1PLbphQpVymmMtcbPcVo3brGuupr%2B34OBrK1elmF5XxdQaQ3cn95JKd%2BBnWoGHb3l%2BFOC9I3vRMMD7k6us6Qy8r7WyxoW%2BzWiqOpFpjc7%2BQWdjbGWddQxCotbVRestTeBCb0N%2FIQzAyTJVEfBBgfJgCnE02SeIV4WNPrwgg5e50zD%2BLpOnVfKV3%2BOgWdFzl6%2B10EG%2B9uyQRsL2Pb3LU5N0wc2WI6NYaKosb396A1ModVmj1lXWzvEi7eV5HozSt9JNmziIRHlPf2mnpR9QdXCz%2BnzSJdS0nXZCqsKgQdNO3uTK2LyuZWx6Y0MeJHrLr6u02G5jrmL3%2FCGjcVlj%2FUVsPkyRbr%2FyEaOCSX9lqu9PbUn7nYM7Wpe0D13dkRh9SK2RdmotTeF0kxSDaW059Iug3wdsA5TzWVZLmPtnKMfV8gSX4szl3KX2TwkuxcEWrw5U3UoX4eikkdkq2LTMkvscnZvscGwEP9jPotbVCuR3qC80RhHjOsofNdn9omKWc2zc2uLdJTOM6QGTPfwsipnFG2jEJuKXec289I2l%2BEYNUjHe3pKjM%2BhudBDchxWYopAAqexEf%2FKCBUdLkmW1aIhY3HxLMV%2BLjKzXO7%2BxEALiW3TKyfRUYx7tsoMb1UeNBpZVhwJbWcK0TOhzaYoPrXKQcOHGQVM88oGQue9cmnf3F%2B8NJhsieYCTaguSbe%2B1w%2B3inGoLeqsZtvDsyOo8Y4UvZvQ6lEJ9PPm6Lcry4%2FJtfylwcPnCPIqIxCnDbdPYRNsfdlFuou6Qe2g1AUhQwjitaYrMogrRzMV8mSG%2B4V%2Fs4keGWEn3gnAW%2Bztm0AGdhAARbr2V7yvi2cMSTMuESbaQrEW%2Bu2SO0hmgxY6sPHDsUsA4CXd0BXcxH35rnpZBwgOiU2yqyKFksI0RlCvQVBXAbrl%2FM0Wc0hmUBVkm6sdMjt0Sgk9kzMwWxp0DDm67xsDpZgnfHG84NuVegweWCfODsGZ3EuvT8toAqzzKYZcnDN1Mld7M%2FMHA53%2FW%2F0tnv1Dqf0mEH%2F4D)

**Comment by bucherfa** [comment]
for later:
- [x] Teachers/Tutors/Coordinators can create Groups/Classes of Students (its own interface) (tracked in #93)

---

for much later:
- [x] make lessons adjustable (tracked in #92)

**Comment by bucherfa** [comment]
[student overview drawio](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R7V1dj6M2FP01ecwK24DJ485Xq65WqjRbVepLxQQnoSUQEZjJzK%2BvPYEkcG8mrJrYzoA0IxEDTnzPtTnHvteM2O1y80serhbfs0gkI%2BpEmxG7G1FKXEpH6s%2BJXqsSEgTbknkeR1XZvuAxfhNVoVOVlnEk1o0LiyxLinjVLJxmaSqmRaMszPPspXnZLEua37oK59U3OvuCx2mYCHDZn3FULLalgXdw9a8ini%2FqbyZOdWYZ1hdXBetFGGUvB0XsfsRu8ywrtkfLza1IlPVqu2zvezhydvfDcpEWXW746x%2F694%2FpyyIdL377Nuezx9kqGpMKn%2BcwKasWV7%2B2eK1NkGdlGglVizNiNy%2BLuBCPq3Cqzr5I1GXZolgm8hORh1V1Ii%2FE5ugPJbvmS8cR2VIU%2Bau8pL6htthr0xVe9vb3J1XZ4sD2blUWVpDPdzXvrSIPKsP8jJEYMNKjWIp1IXICrCXbXTRNEibxPJXHU9l%2BkcsCZZ1YutjX6sQyjiJ1%2B00u1vFb%2BPRelbL1KovT4r013s3Iu1N1lUW23nYSVfW6yLN%2FxW2WZLLeuzRLVS2zOElaRedAxWuiQiEqHAGFXgwU97TnFnkcpvN3055w2zwrwiLOFBoT5zwG48FJNyZavZjb39Wp07Gvk8uZKQBmog4lY0LG1O%2FQ27t2ye6jAgZDE6hzIOG2kMBGXQQIdjEcJha6a9tIHjSSh42CF7NS3X8OrES%2ByM%2BPhbJMfx5OfhsYz%2BzTqW6C1d4bGPdeyD4H71XAmPZeSHjFJlwCQKSkWalD2dQwSUSSzXN5lTSuyGP5SxQizXO%2F70%2BccvhZvBG1HiQt048om81mdDoFOMkzkf%2Fke%2F55kHH5aWSwp%2BLlkIGsVzZlPV2USRTPC4CQrFIq5Q4E%2BAzG8slpY2Fc7nLG8iwchFuMlzHjjLemtT1nvMw1zHipjQKtbSTznAHqs4EzKGBMc4Yr0GsuImr1em9d8eC9LWAMey%2BDem1gvMeQ0cp4GdSI1jJezFhaGa8L3fhBLJI3IS2R9md0qYl%2FPfPO4bCvdXRxoQ%2Ff7324TOc9BsedQHAItjByOXTgbId55tKSiR6y3KZ3EdSFMw87lSjb4ozl%2F0%2FJxk%2FizqwFFKLnd0unetwZyvlIJJKCGH1Ucrft0N14xcWYuGuj2m73et94r%2F9gNVT1%2Bl6Kl9YTzEPoxW5Y0NPlofa2scv7hrt8PQw3uryfKCeN4md5OFeHijAXKiqsOiW%2F6uAscgOvy57y9lXtey0bXzDHpQgi%2FsUQwZZJgYGj8DmTBNn5Iz1Qft2NDuojVwMY5bYBBpXMkS60fn8opP8DJvdqYHKJbTBBSVN3ojJtTp8cM%2FFVAuF5tgEBVdP3cCMLlqUKH12GaRflf6UrbEGTJ40xpa919t2DC8I%2FJI3M43I5Yl8Vna0jHz4jHJx%2FaQGCyAvNgECtKuuRj45ItYk%2BlKW8%2FdMC0hYSY4oFA2jFw0ZRzBhtO67xlAAP6uIepgQwf4eMqal1r8Oys9E0ADKZdHFfrakA9ZhieTd3sQkDvbFRPhSovYiNYh4AgxuevfEx6WncaYGdPGQNWG%2BMiQ%2FFXy%2BnaRkH2JhOWvM7JK3Z4MOucR%2BGSm3w4eYUhzEfhpqtn6FSxA%2B6gKM1WsqHAs6aaCkS0C720how5UMdZ8GADJiwNzHPhKHQ6ikT9h3DTJhbKd%2BgnYyzCA7V28AittiYZhH8OtScj6hezT48qLljPozkIun1YSQZc2DCx8HRyoQ5VJA2M2HMXlqZMIeyro%2BpA4y1V0ldZniJg0NN19%2FsAYgPR%2Fb60JtAwK9DRHJs8wKtq6b8Aw3Z6xwCF2CFCH69aQQBFJkWxBSTCaDoHAkr0irHAxv3%2BoHdP8AyLrR2%2FwBqviGZAD7QAoRw6M0nCJDwUSv7fmA6YCrAFvR6lVKATFabDroNoPQbsgoa22LAhSvjmGGRoL1PLCA%2BXDIzjhSUo73ILSDctw8LqDz7k15A6AREtBMstFLrfH0ANW6PcgzIbtKyRgSZ19QLyAQK2W9JWK7LfNbH%2BU3a7jME27FA6%2FwZca5jAo10Tce%2F4O7kzhCG8cGuPnp3KCdwZLHAbYGhsK3c9a5hEzIEYmzBAYvY1PTOd8TKV8AgXoxsz6rbi4dQjGNejIR6afbiIRajJilgcgdDR2ssBiFwRs7mYAzMYFqDMQjBpsOMD8qAEVNs7U0zI0bea9RTRsywtyfpfUJaKeSgoSzgElDHDVyiAsc0l0BeqmSlFyMCWLMX00HXHfNiJHBcsxdDXTcw4g%2FQ0cuIsVcsWcyIMYOdiRHLj%2FuX4L6fO3iXMLv%2FDw%3D%3D)
