### ISSUE TITLE
As a user, I want to have helpful information and links displayed to me on the home page of the application, in order to get work done more quickly.

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#41]
13 SP

**Comment by robKoh** [comment]
Implementation started on Monday, 22.11.2021.

Link to Mock-Up: https://app.artboard.studio/project/61929b2e61bf25001d1d5fb0
Link to Google-Docs: https://docs.google.com/document/d/1j5TuRfuMPUUSY0Mcki0Cn7lwr5R2r_QxAuN3oFVjWnk/edit?usp=sharing

The Google-Document contains thinkings about the current application design.

**Status:**
The design of home page for Coordinator is implemented.
Furthermore you can click on image to navigate to other pages now.
I implemented the design of home page for teacher.

_NOW_
This feature is nearly finished, we must wait for further implemented pages to embellish these designs.
