### ISSUE TITLE
As a user, I want to have access to a step-by-step guide for tasks that the application can perform, so that I can easily get started using the app.

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#43]
8 SP

**Comment by bucherfa** [comment]
### Lehrer

- [x] Anmelden
- [x] Abmelden
- [x] Fehlzeit eintragen
- [x] Fehlzeiten anschauen/korrigieren

### Lehrer mit Tutorium

- [x] Fehlzeit entschuldigen (Direkt + über Modal)
- [x] Entschuldigungen anschauen/korrigieren
- [x] Tutorium anschauen

### Koordinator

- [x] Schüler importieren
- [x] Schüler hinzufügen/editieren/löschen
- [x] Tutorium erstellen/editieren/löschen
- [x] Zeitspanne erstellen/löschen
- [x] Klausuren entschuldigen
