### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by axelkrusechavela** [LAM-GeMont/fehlzeiten#46]
Due on 7.12.

**Comment by bucherfa** [comment]
[simple Architekturüberischt](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R3Vpdc6o4GP41zrQXdggfai9rW892Tne3O85uTy8DRMgREjaEqv31m0AQMIqeHkX3zHQ6yUsSkufJ%2B4k96z5efmEwCX%2BnPop6puEve9ZDzzSBbZo9%2BWf4q0IydJxCEDDsq0GVYIo%2FkBIaSpphH6WNgZzSiOOkKfQoIcjjDRlkjC6aw2Y0ar41gQHSBFMPRrr0Ffs8LKQjx6jkvyEchOWbgaGexLAcrARpCH26qImsx551zyjlRSte3qNIglfiUsyb7Hi63hhDhB8ywUn%2Fec3%2BxcCwP16Mr6E7J2%2BgbxWrvMMoUwceQ2%2BOiK%2F2zFclEGL7iWxmcTRhMBbN8SLEHE0T6En5QvAvZCGPI9EDoqmWRoyj5c49gzUS4gohGiPOVmKImmCXOKvbY5X9RcWFNVCysMaDWQ6Eiv9gvXYFkWgolH4AMVNDbMIo4ZcD2cUhNtKAQb7QMdWljIc0oARGj5V0zGhGfCRXNUSvGvNMaaKw%2Bo44XymDATNOm0iiJebfau03udSN6ajuw1ItnXdWZYeI836rd%2BrTZL%2Bal%2FfKicUJ5bHaWRMo0Ix5qAUtWxk5yALEW8Y5228BQxHk%2BL25j%2BMrwaCVU0LJUUk0GiQODyQRNEkc7iNRqPCd9Bii60UwTbFXCCc4aupnpzyD0VmJvu2EaB%2BmYT4fdM6DeSgR9jl5sAzN7dy5LJshIoVU%2Fn8iM8pE1IEFJ2Qra8%2FQFdFZA3gY4YBIoAVuiAmB9D1YhD936kGMfb%2BwyCjFH9DN15MsJxQTnh%2FTGfechzbnpWIzNbmKiOp0tdy%2Bna6ub9xYQ%2Fu24e%2FUKw9mRS3%2BIk9TrTxqOtG%2Bddtcgc5mqbgsm6yut%2Fh5om2N56kXEsx5kpG5eOMgEoCNXSZaAc9BLyQ%2Bfi9FV4%2FLRLCV9iTOYoCRh%2BZ%2FPV%2BXY8XGasO1q1JpM%2BgmYjGdBtrrfi1kAeaWkGVwqoil3eidOGLpxtkd0YI6%2FwcDCtojlkuKQs9ADfhZbvKpwmvDVW2AchE7rexwI7uz7Y0M9sfGi0axg6MaZEczyFtM7gMUCaALyby%2Fy8ZqUyBxMfEzElyoVXY2fOD5rTIYXoxZ3qm%2FA6uy2C%2BIYXFyGVZdjK0GXaWXnzMI1sadG4LTKzjQQ65cnft6sCU1XLuDZZXHW0VCoRGz9qunW1zKZ3ctgN48yK%2FqnxkXyyAlT4tbCZzj6PRwozhkG4MbXau3VYdunRMptWm2WLrPqmyVQKoEtcoej61PowP1aRczHaXxTqvpPHa9ppuiW7d1goOZPmuYa7b7yKMX5ipv91Z7tIvovXw16kBnUdPzsjfSXNErEp6EReJ%2FHir%2BElWdYauTklUd%2B9ZqOKryq8tPlnXW3qb8OLIRqp6urAN0ZvNPQgvK5nqccfUHWvKb7%2Bl1i2%2FsJgswN1Ous2cBptWNhesuhijhu%2FRPAXoJekta%2B5XGiSxA1wPovbmwi90IUx6i%2BcFTru5DOGdQ7Ofvp%2BvdZdE9SbU4Nk5S1IkqDQ6Jvbfq0uhkugQOoXRCWZxFkLkwxQKA7dBeyVF4rlusLiEGG%2FmjY%2BgfvztGWE8un6aIvbfAtM4nI5r5ncBmDZuwDcDpYOvJn0uUP3kpvGv1wyHr8T8%3D)
