### ISSUE TITLE
As a teacher, I want to enter the absences of a student by hour in the class I'm currently teaching in order to archive them.

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#6]
40 SP

**Comment by jonaslanglotz** [comment]
A teacher must be able to mark an absence as _during an exam_ in order to fullfill #8

**Comment by EricZimmer1** [comment]
- create entity and resolvers for 'absence' in backend
- create mutations and queries
- create creation flow in ui

**Comment by bucherfa** [comment]
- date selection (default: today) [functional]
-  lesson selection (checkbox group) [functional]
- student selection [functional, placeholder]
  - missing: connect to all students endpoint

**Comment by bucherfa** [comment]
[design ideas](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#R7V1tb6NGEP41%2FtiK3eX14yXpXaUqUqu0qnTfOLMx6LBxMY6T%2FPpCDNjM7MVry%2FtCuE9x1ngwzwwz88wM6xm7XT5%2FKeN1el8kPJ9RJ3mesbsZpcQPWP2nWXnZr4RhuF9YlFnSHnRYeMheebvotKvbLOGbwYFVUeRVth4uzovVis%2BrwVpclsVueNhjkQ%2FPuo4X7Rmdw8LDPM45OuzfLKnS9iq8o6N%2F59ki7c5MnPadZdwd3C5s0jgpdkdL7LcZuy2Lotq%2FWj7f8rwBr8Nl%2F7nPP3i3%2F2IlX1UyH1hmAbvLnuP1P6unv5j38uWrx3%2Fx3b2YpzjftlfcftvqpYOgLLarhDdSnBm72aVZxR%2FW8bx5d1crvV5Lq2Ve%2F0fql49Znt8WeVHW%2F6%2BKVX3QTXsGXlb8%2BYffnfSI1KbEiyWvypf6kPYDUYtha0SUuO3C7qAT1iGfHusjbBfj1g4WvewDVPWLFq1zkGNXRu4KMPkApn7hGCZPBBNTBRMZhX15Q%2BCYJGyBowo2OgrYwiFsgeRNqczYrn1LqkHNtc7acBDYzNPZLZvd3Oa8JFaCCGxP5Om02p43DtsDsEWycZQoi6OnceOr5FOTyh2QOMJpCOr%2Bszzpkjp5gI4QEN183VrJ87jKnobiRaC0Z%2FizyOoTHwWaIf4I102xLee8%2FdRxNgcEBd4JQVVcLniFBL3pqL%2Fsy9UWTEptBKitD3Xnqo15JwQpVls4KbWhu811f%2FWudL9hUYpVF50TYIglKSGhOMCEAoVTVeGlc4uWw0YC23A7i7gZww1SXvO4STC3Wky23nBTmDEXxCBB7ky1YibB2wxj1vOGd%2BxML2YShTvTdkZtw2wcHA2G0BDDJuZonjLgJEiafcD1ubaxmgDBLOmPPN7UtyR17uMq5QjF%2BuKrIVRxni1W9et5DQKv8bppIMrmcf6pfWOZJUnz8ZuSb7LX%2BNubqEYH6yYTfbsk72bm3TWytlWx2bdYGtGbqiy%2Bc6AHLQV8Iqg7RFpdwbSIEOKv0OQv5q9QkGISRCRYkOmwB9Mr02GvE%2FyOF3JwjXcinoh5HtIOEQUJdeoZR4sMBFeXmA6uHUxHuH3K8%2BmEVNKls71GsCW7Wg15HO03UDEIRem15mavBC%2F5UMnI0HCJ41%2BcjZySpDgdoWcRI3NF2SFMkcB3ay2SUYnukQWwkcA23CRYiwW4Ud823MbAGqArE1QvtNIGhmmDbaDVAeCkoenFTCKXN21o1DbMcB7%2FjlMzx38AbLLDbuqqsmwc%2BTYAjkjP7qobE8S9k6mWZYFRC7iQ1rIsmzoTgshezoSgJMVMiMnM8ZlOsUATovc6xkLf6f7QlCqzKFCYLs2ys%2FiWNRGWCuxa89MxDDOuaRVn8eyD4eqsi%2BncfTvin9c4W2jWsGlJqCBz7AdotWSOrgy%2F%2B0j5CYyYl46rw74xlqQ4P3ElWOaH1hykoZdrDkpSrblx0Fw4iOqLHq3R%2FFiXzIzgB7J5AlQQQmSlbR4qE0lSbfNnTSra0lc6VPVNFfrdcfTjYGPJAuDG0ZGDnSULgJMZJDRc94ARPBCEJq11D9f%2BfhxsLQktTStonRYtBg32liwAbRzDdXA8OpCdrlPXXfIkCJOFyAnHufRuBID5ykS7S4iEBoJRaK39JW%2FijCi4eNIOMiIkSTEj8mQ6g6b7SyD6OaJ6pVZzx3Rowv0l5I7C0HSDyTuLdlkTZCPz2695mHdNrMHkQZ0YbjB5mNRZ32CCGIroitYGUxdVp5KgODBkXt6mOCVJcYLiT601CPGOrqY5KEm15saxLQCJQP7CiOymdwp3Qb32zgDXACoEm%2BkwURlK8z6o%2FjgyPYQdFZai9PYx%2FYk9rB%2BB4SEaXjoWivaVwqJUO9dxbFtGQjB9yETDoVo7S4FEKmgDclFoHXJnFf3NNTOdwDrkqISnNdyYI3CX89D0E0zBCPYvc1wJW9OLmv07mDXDbrahNlKyQgPRNud6W5rBOLYxw9hFsgP9yuhL8HMns147BFq2oBqutasZTJ0fBbC%2BcTk%2FQqJU76M%2BglEoAip0zDG9Y2ynpJ%2BNTbFLigRPG%2BntbIbjGLwSxFrzRdUQs7Bp9TYjOHwZ%2BYabmyGmeLY3NyMCvbaIu2jtboYTG7%2FCKrj0d0Mo8U%2BJUv3LIRPbmgHp7uKf6sG60%2F1jPSEmvjueVe86LnNlUQL22mdMsNeOXr%2BF2e%2FXGj8r3T7%2BhSHB0C0TVZXVNfBCTFD%2FjhfxdrOL0%2FyDodjnJddHEVPFh6qBajUqJIUJtl4kI0xO7PWHxHehPxSMM2j1hxEmKDbaHhxap77A9ISeEA63Xw85%2B1tFDD6cKpr2FWZenirQMG34zNP89S0EO497Hlbfu06S8bcS0N4t1i%2B%2BzbcpX9lom9QDxsmETwuI6sjqGiQRzvH%2F22bz7%2FG8ygoM40etP1APVoVFuz1qbcxHOIMX3wI5r16r0d4DlOI6z9XugfrfsiiqY2pVX2h6XyS8OeJ%2F)
