### ISSUE TITLE
Import students from csv file (coordinator only)

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#82]
- [x] @axelkrusechavela gets the example csv file
- [x] implement import for csv file (fe + be)

**Comment by bucherfa** [comment]
the csv file will most likely look like this:

```csv
Name; Vorname; Klasse
Mustermann; Max; 10b
Müller; Moritz; 11a
```

**Comment by axelkrusechavela** [comment]
I think it doesn't include the exact class/tutorium but just the year e.g. '10' instead of '10b'. But I'll try to ask that again.

**Comment by axelkrusechavela** [comment]
She confirmed that it is only the year. We agreed that we'll ignore it as it has no use; the tutorium needs to be assigned manually anyway.
For me it sounded like she can control which properties are exported into the .csv so maybe she'll throw the year out by herself.
I propose you just assume 'last name; first name' and then jump to the next row, regardless of if there are other columns or not. Maybe just put a quick note label above the import feature showing the expected pattern.

**Comment by axelkrusechavela** [comment]
A bit off topic: she agreed that if there are students with the same name, she can just add the birthday or something to the last name for differentiation. We don't have to worry about that.
