### ISSUE TITLE
Create an overview page for a student

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#83]
- [x] add an action/link to student list to reach an overview page
- [x] /student/[uuid]
- [x] display name of student
- [x] display tutorium (if available)

**Comment by jonaslanglotz** [comment]
See here for more info on how to do the dynamic routing: https://nextjs.org/docs/routing/dynamic-routes

pages/student/[id].tsx
```tsx
import { useRouter } from 'next/router'

const Student = () => {                              // This is your page component
  const router = useRouter()
  const { id } = router.query

  return <p>Student: {id}</p>
}

export default Student
```

**Comment by EricZimmer1** [comment]
Moin @ItsMihail,
ich hab die Seite erstmal verlinkt, weiter bin ich leider noch nicht wirklich gekommen. Du findest die Änderungen im branch feature/create/overview-page
