### ISSUE TITLE
Student Overview: List of absences

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#84]
- [x] list all absences
- [x] action: mark an absence as excused
- [x] delete absence (Coordinator, Tutor, Teachers only their own submitted once)
- [x] ~exclude absences that are marked as an exam~
- [x] grouped by semesters

**Comment by ItsMihail** [comment]
marking an absence as excused has been prepared; waiting for implementation of semesters

**Comment by bucherfa** [comment]
@ItsMihail implementation of semesters is now in dev

**Comment by EricZimmer1** [comment]
semester grouping implemented, waiting for excuse implementation

**Comment by EricZimmer1** [comment]
@bucherfa Zum Punkt 'exclude absences that are marked as an exam':
Wäre es nicht besser die Abwesenheiten trotzdem für den tutor anzeigen zu lassen? Entschuldigen kann er sie zwar nicht aber für eine Übersicht wäre das denke ich von Vorteil. Oder hatte das einen anderen Hintergrund?

**Comment by bucherfa** [comment]
da hast du wahrscheinlich recht. ich glaube nicht, dass es einen anderen Hintergrund gab.

**Comment by bucherfa** [comment]
diese issue ist jetzt auch vollständig auch abgedeckt von #135, oder?

**Comment by EricZimmer1** [comment]
Jo ist durch.
