### ISSUE TITLE
Behavior for a new absence where an absence already exists but without the exam flag

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#96]
Should the absence be upgraded to an exam absence?

**Comment by jonaslanglotz** [comment]
I think we should avoid such default behaviour in an edge case like this, where it is hard to revert. I would suggest we implement an optional flag in the mutation, such as `overwriteOnDuplicate`. Using this, we can usually leave it unset. When we do encounter a duplicate error, we can then ask the user if he wants to overwrite the existing absences using a modal. If the user confirms, we can then simply resend the mutation with the flag set.

**Comment by jonaslanglotz** [comment]
Do you want me to implement this?

**Comment by bucherfa** [comment]
I think we will see about that once we talked about #97
